### ISSUE TITLE
refacotor: 학점이 바뀐 과목에 대한 조치

### ISSUE THREAD

**Issue by gmltn9233** [Sejong-Java-Study/gonghak98#58]
**이슈가 필요한 이유**
현재 **학수번호를 PK**로 `Course` 테이블에 학수번호, 과목명, 학점을 저장하고있는데, **년도가 달라짐에 따라 학점이 달라지는 과목이 존재**함을 발견했습니다. 이에 `Course` 테이블 **리팩토링** 혹은 학점이 바뀐 **17년도를 서비스에서 제외**시키는 등의 리팩토링이 필요합니다. 

**마감 기간**
-

**Comment by gmltn9233** [comment]
### 학점이 달라지는 과목
![image](https://github.com/user-attachments/assets/79eced8d-5aa8-40b8-a70b-12412575f7ac)

17~24 학년도 수강편람을 참조하였을때 학점이 변경된 과목은 **'문제해결을위한글쓰기와발표'** 와 **'문제해결을위한글쓰기와발표'** 2과목인 것으로 확인되어 **17학년도를 서비스에서 제외시키는 방식**이 가장 합당해보입니다.

### 교과목명이 달라지는 과목
![image](https://github.com/user-attachments/assets/ef9aba79-a121-4d81-95b1-494ce68dba7d)

18~24학년도 까지 교과목이 변경되는 과목이 있습니다. 허나 현 DB의 `Course` 테이블은 학수번호를 PK로하여 **학수번호는 같지만 교과목명이 다른 과목들을 저장하지 못합니다.** 그래서 `Course` 테이블의 PK를 **학수번호, 교과목명 2개의 Multiple PK**를 사용하는 방식으로 변경하려고 합니다.

**Comment by jiseop121** [comment]
문제해결을위한글쓰기와발표' 와 '문제해결을위한글쓰기와발표' -> 문쓰발과 서철을 말씀하신거죠? 17학번을 위해 추가 로직에 할애하는 시간에 비해 얻는 수요가 극히 작을 것으로 생각되어 17학년도는 제외시키는게 맞다고 봅니다.

**Comment by gmltn9233** [comment]
> 문제해결을위한글쓰기와발표' 와 '문제해결을위한글쓰기와발표' -> 문쓰발과 서철을 말씀하신거죠? 17학번을 위해 추가 로직에 할애하는 시간에 비해 얻는 수요가 극히 작을 것으로 생각되어 17학년도는 제외시키는게 맞다고 봅니다.

넵 문쓰발과 서철이 맞습니다. 의견 감사합니다👍
