### ISSUE TITLE
기이수파일 재업로드시 권한오류

### ISSUE THREAD

**Issue by gmltn9233** [Sejong-Java-Study/gonghak98#76]
**이슈가 필요한 이유**
현재 기이수파일을 이미 업로드한 적이 있는 상황에서 다시 업로드하려고 시도하면 **403 에러가 발생**합니다.
이유는 살펴봐야겠지만 업로드한적이 없는 유저는 `XSRF-TOKEN`이 존재하지만 업로드한 이력이 있는 유저는 `XSRF-TOKEN`이 소실되어 에러가 발생합니다. `XSRF-TOKEN`은 CSRF 보호에 관한 문제라 get,post 방식의 문제인것으로 추정됩니다.
### 1. 업로드한 이력이 없는 유저
![image](https://github.com/user-attachments/assets/66a6a63e-89f7-47b2-bab8-8eb73fe0d8f7)

### 2. 업로드한 이력이 있는 유저
![image](https://github.com/user-attachments/assets/7e5173fa-e5ce-4e92-ae02-2781db50894a)

다행인건 신규유저의 경우는 오류없이 진행가능해서 당장 서버를 내릴 정도는 아닌것 같습니다 ㅠㅠ
내일중으로 검토하고 수정해보겠습니다!

**마감 기간**
- ~09/27

**Comment by whxogus215** [comment]
EC2에서는 어떤 에러로그가 남는지 확인했나요?

**Comment by gmltn9233** [comment]
> EC2에서는 어떤 에러로그가 남는지 확인했나요?

로직오류가 아니라 CSRF 토큰 소실로 인한 403 에러라 에러로그에 따로 남지않은거 같습니다ㅠㅠ
