### ISSUE TITLE
기이수 과목 학수번호 관련 오류

### ISSUE THREAD

**Issue by gmltn9233** [Sejong-Java-Study/gonghak98#82]
**이슈가 필요한 이유**
기이수 성적 파일 업로드 시 "F02754" 등 예상치못한 학수번호 입력시 오류가 발생하고 있습니다.
![image](https://github.com/user-attachments/assets/ba90cedf-7150-4ea0-9f02-d889a52f7a90)

학수번호가 DB에 존재하지 않을 경우 continue 하도록 설계해두어 문제가 발생하지 않을 줄 알았는데, 입력받은 학수번호를 `Long` 타입으로 변환하는 로직에서 기존 **인턴십과목(P로시작)** 만 예외처리가 되어있어, 문제가 발생했습니다.

공학인증 로직에 쓰이는 소융대 과목은 `0~9` 혹은 `P` 로 시작하기 때문에 제외해도 로직에 영향을 끼치지 않으므로  **기존 과목(0~9), 인턴십 과목(P) 을 제외한 영문 입력은 전부 예외처리** 해도 좋을것 같다는 생각입니다.

**마감 기간**
- 10/16

**Comment by whxogus215** [comment]
![image](https://github.com/user-attachments/assets/21c610a8-9fab-4c1f-8c2d-3b4a484b7685)

P로 시작하는 과목(현장실습)을 제외하고, 문자로 시작하는 학수번호를 갖는 과목들은 체크 대상에서 제외시키는 걸로 결정!
