### ISSUE TITLE
AbeekType이 잘못 기입된 교과목 존재

### ISSUE THREAD

**Issue by gmltn9233** [Sejong-Java-Study/gonghak98#88]
**이슈가 필요한 이유** 
이슈 https://github.com/Sejong-Java-Study/gonghak98/issues/83 을 진행하던 와중에, **고급프로그래밍입문-P** 과목의 `AbeekType`이 **전문교양**으로 출력되는것을 확인하였습니다.

![image](https://github.com/user-attachments/assets/4b3c98da-0f69-44c6-a006-7191590ce833)

csv파일을 확인해보니,  **고급프로그래밍입문-P** 과목의 `AbeekType`이 **전문교양**으로 되어있어 수정이 필요하며, 이슈 https://github.com/Sejong-Java-Study/gonghak98/issues/83 을 진행하며 추가적으로 해당 오류가 있는지 확인이 필요합니다.

![image](https://github.com/user-attachments/assets/b1f9924d-d338-47ab-b053-4211a0a1f862)
(고급p 학수번호 9790)

**마감 기간**
- 11/25

**Comment by whxogus215** [comment]
그러면 **고급프로그래밍입문-P** 과목의 Abeek 영역은 무엇으로 변경되어야 한다는 건가요? 공학인증 사이트에 찾아보니 **고급프로그래밍입문-P**에 대한 영역이 안보여서요!
